apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "67"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{"deployment.kubernetes.io/revision":"10"},"name":"north","namespace":"qr-demo-qa"},"spec":{"progressDeadlineSeconds":600,"replicas":1,"revisionHistoryLimit":10,"selector":{"matchLabels":{"app":"north"}},"strategy":{"rollingUpdate":{"maxSurge":"25%","maxUnavailable":"25%"},"type":"RollingUpdate"},"template":{"metadata":{"annotations":{"kubectl.kubernetes.io/restartedAt":"2026-01-20T22:51:35Z"},"creationTimestamp":null,"labels":{"app":"north"}},"spec":{"containers":[{"args":["pip install --no-cache-dir flask \u003e/tmp/pip.log 2\u003e\u00261 \u0026\u0026 python /opt/app/app.py"],"command":["bash","-lc"],"image":"registry.access.redhat.com/ubi9/python-311:latest","imagePullPolicy":"Always","name":"north","ports":[{"containerPort":8080,"protocol":"TCP"}],"resources":{},"terminationMessagePath":"/dev/termination-log","terminationMessagePolicy":"File","volumeMounts":[{"mountPath":"/opt/app","name":"app"}]}],"dnsPolicy":"ClusterFirst","restartPolicy":"Always","schedulerName":"default-scheduler","securityContext":{},"terminationGracePeriodSeconds":30,"volumes":[{"configMap":{"defaultMode":420,"name":"north-app"},"name":"app"}]}}}}
  creationTimestamp: "2026-01-21T08:38:12Z"
  generation: 68
  name: north
  namespace: qr-demo-qa
  resourceVersion: "1872254"
  uid: 1b4f5c26-a871-4824-a590-f0aa6a801bf6
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: north
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/restartedAt: "2026-02-17T10:46:26-05:00"
      creationTimestamp: null
      labels:
        app: north
    spec:
      containers:
      - args:
        - pip install --no-cache-dir flask >/tmp/pip.log 2>&1 && python /opt/app/app.py
        command:
        - bash
        - -lc
        env:
        - name: GIT_COMMIT
          value: 10fbdd5
        - name: BUILD_VERSION
          value: "1.0"
        image: registry.access.redhat.com/ubi9/python-311:latest
        imagePullPolicy: Always
        name: north
        ports:
        - containerPort: 8080
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /assets
          name: assets
          readOnly: true
        - mountPath: /opt/app
          name: app
        - mountPath: /stage
          name: stage-dashboard
          readOnly: true
        - mountPath: /south-ui
          name: south-ui-html
          readOnly: true
        - mountPath: /data
          name: data
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - configMap:
          defaultMode: 420
          name: north-assets
        name: assets
      - configMap:
          defaultMode: 420
          name: north-app
        name: app
      - configMap:
          defaultMode: 420
          name: north-stage-dashboard
        name: stage-dashboard
      - configMap:
          defaultMode: 420
          name: south-ui-html
        name: south-ui-html
      - name: data
        persistentVolumeClaim:
          claimName: north-data
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2026-02-18T21:26:39Z"
    lastUpdateTime: "2026-02-18T21:26:39Z"
    message: ReplicaSet "north-f5f9db7c6" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  - lastTransitionTime: "2026-02-19T10:12:49Z"
    lastUpdateTime: "2026-02-19T10:12:49Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  observedGeneration: 68
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
