apiVersion: v1
kind: Service
metadata:
  name: north
spec:
  clusterIP: 172.30.154.188
  clusterIPs:
  - 172.30.154.188
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: north
  sessionAffinity: None
  type: ClusterIP
