apiVersion: v1
kind: Service
metadata:
  labels:
    app: south-ui
  name: south-ui
spec:
  clusterIP: 172.30.238.131
  clusterIPs:
  - 172.30.238.131
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: south-ui
  sessionAffinity: None
  type: ClusterIP
