apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: south-ui
  name: south-ui
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: south-ui
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/restartedAt: '2026-02-15T23:15:12-05:00'
      labels:
        app: south-ui
    spec:
      containers:
      - env:
        - name: NORTH_URL
          valueFrom:
            configMapKeyRef:
              key: NORTH_URL
              name: south-ui-env
        image: registry.access.redhat.com/ubi9/httpd-24
        imagePullPolicy: Always
        name: httpd-24
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /var/www/html
          name: html
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - configMap:
          defaultMode: 420
          name: south-ui-html
        name: html
