apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: qr-demo-qa
resources:
  - ../../base
patches:
  - target:
      kind: ConfigMap
      name: south-ui-env
    patch: |
      - op: replace
        path: /data/NORTH_URL
        value: https://north-qr-demo-qa.apps.cluster-nlthm.nlthm.sandbox3528.opentlc.com
